name       : haskell-optparse-simple
version    : 0.1.1.2
release    : 3
source     :
    - https://hackage.haskell.org/package/optparse-simple-0.1.1.2/optparse-simple-0.1.1.2.tar.gz : 02716473cc57ff1212c5174cc213f5b1bb744e680c222a4ae97e0b12f38400e4
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple interface to optparse-applicative
description: |
    Simple interface to optparse-applicative
builddeps  :
    - haskell-cabal-install
    - haskell-githash-devel
    - haskell-gitrev-devel
    - haskell-optparse-applicative-devel
rundeps    :
    - devel:
        - haskell-githash-devel
        - haskell-gitrev-devel
        - haskell-optparse-applicative-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
