name       : haskell-optparse-simple
version    : 0.0.3
release    : 1
source     :
    - http://hackage.haskell.org/package/optparse-simple-0.0.3/optparse-simple-0.0.3.tar.gz : 4547f0a6c1bd959b1d9c3c2a5fabee39ac9a19dffabbb2d75461a2d461df8c7e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple interface to optparse-applicative
description: |
    Simple interface to optparse-applicative
builddeps  :
    - haskell-cabal-install
    - haskell-either
    - haskell-gitrev
    - haskell-optparse-applicative
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
